"""create movements

Revision ID: 0d2617e2e2a4
Revises: 80ee4920c4d7
Create Date: 2026-03-11 08:12:35.787131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2617e2e2a4'
down_revision: Union[str, Sequence[str], None] = '80ee4920c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesos',
    sa.Column('id_proceso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tipo_proceso', sa.String(length=50), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('id_proceso')
    )
    op.create_table('movimientos_productos',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('id_proceso_origen', sa.Integer(), nullable=False),
    sa.Column('id_proceso_destino', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.ForeignKeyConstraint(['id_proceso_destino'], ['procesos.id_proceso'], ),
    sa.ForeignKeyConstraint(['id_proceso_origen'], ['procesos.id_proceso'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('stock_quimicos',
    sa.Column('id_stock_quimico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.Column('cantidad_minima', sa.Float(), nullable=False),
    sa.Column('cantidad_maxima', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.ForeignKeyConstraint(['id_proceso'], ['procesos.id_proceso'], ),
    sa.PrimaryKeyConstraint('id_stock_quimico')
    )
    op.create_table('alertas_stock',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('id_proceso', sa.Integer(), nullable=False),
    sa.Column('id_stock_quimico', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('cantidad_actual', sa.Float(), nullable=False),
    sa.Column('cantidad_referencia', sa.Float(), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.ForeignKeyConstraint(['id_proceso'], ['procesos.id_proceso'], ),
    sa.ForeignKeyConstraint(['id_stock_quimico'], ['stock_quimicos.id_stock_quimico'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_stock')
    op.drop_table('stock_quimicos')
    op.drop_table('movimientos_productos')
    op.drop_table('procesos')
    # ### end Alembic commands ###
