"""add limite critico to products

Revision ID: 4b3f454a5135
Revises: bfa32e90254d
Create Date: 2026-03-29 08:33:30.647773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3f454a5135'
down_revision: Union[str, Sequence[str], None] = 'bfa32e90254d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('limite_critico', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'limite_critico')
    # ### end Alembic commands ###
