"""create others tables

Revision ID: 80ee4920c4d7
Revises: 59fea0ecb9c7
Create Date: 2026-02-22 19:18:47.069449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ee4920c4d7'
down_revision: Union[str, Sequence[str], None] = '59fea0ecb9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('codigo_cliente', sa.String(length=50), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('telefono1', sa.String(length=20), nullable=False),
    sa.Column('telefono2', sa.String(length=20), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('tipo_agua', sa.String(length=50), nullable=False),
    sa.Column('cantidad_promedio_kg', sa.Float(), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('codigo_cliente')
    )
    op.create_table('proveedor',
    sa.Column('cad_proveedor', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=False),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('cad_proveedor')
    )
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=False),
    sa.Column('posicion', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('tipo_ubicacion', sa.String(length=50), nullable=False),
    sa.Column('localizador', sa.String(length=100), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_table('producto_proveedor',
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('cad_proveedor', sa.String(length=50), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cad_proveedor'], ['proveedor.cad_proveedor'], ),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('codigo_producto', 'cad_proveedor')
    )
    op.create_table('stock_almacen',
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.PrimaryKeyConstraint('codigo_producto')
    )
    op.create_table('stock_ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('codigo_producto', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_producto'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['companies.id_company'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id_ubicacion'], ),
    sa.PrimaryKeyConstraint('id_ubicacion', 'codigo_producto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_ubicacion')
    op.drop_table('stock_almacen')
    op.drop_table('producto_proveedor')
    op.drop_table('ubicacion')
    op.drop_table('proveedor')
    op.drop_table('cliente')
    # ### end Alembic commands ###
