"""Add product provider price and movement type

Revision ID: bfa32e90254d
Revises: 0ee3ceb44209
Create Date: 2026-03-29 08:10:59.929794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa32e90254d'
down_revision: Union[str, Sequence[str], None] = '0ee3ceb44209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos_productos', sa.Column('tipo_movimiento', sa.String(length=20), server_default='traslado', nullable=False))
    op.add_column('producto_proveedor', sa.Column('precio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto_proveedor', 'precio')
    op.drop_column('movimientos_productos', 'tipo_movimiento')
    # ### end Alembic commands ###
