"""add_logo_to_companies

Revision ID: c33156a66ff2
Revises: 4a345fb2de61
Create Date: 2026-05-19 12:38:17.369095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33156a66ff2'
down_revision: Union[str, Sequence[str], None] = '4a345fb2de61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo')
    # ### end Alembic commands ###
