"""firts migrate

Revision ID: c670001c78e5
Revises: 
Create Date: 2026-02-06 20:10:03.772293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c670001c78e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id_company', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_company'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('products',
    sa.Column('id_product', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('unit_measure', sa.String(), nullable=False),
    sa.Column('unit_price', sa.String(), nullable=False),
    sa.Column('min_unit_price', sa.String(), nullable=False),
    sa.Column('lead_time_days', sa.String(), nullable=False),
    sa.Column('restorage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('roles',
    sa.Column('id_role', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('users',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('companies')
    # ### end Alembic commands ###
