"""create relations

Revision ID: e02237b296d0
Revises: c670001c78e5
Create Date: 2026-02-07 09:59:03.114234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02237b296d0'
down_revision: Union[str, Sequence[str], None] = 'c670001c78e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id_company'])
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id_role'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id_company'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    # ### end Alembic commands ###
